services:
  front:
    build: .\front\
    ports:
      - "8080:8080"
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  back:
    build: .\back\
    depends_on:
      - db
    environment:
      DB_HOST: postgres
    ports:
      - "3000:3000"
  migration:
    build: .
    depends_on:
      - back
      - db
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "db:5432",
        "--",
        "npm",
        "run",
        "migration:run",
      ]
    environment:
      DB_HOST: postgres
